#!/usr/bin/env sh
# -*- sh -*-

: << =cut

=head1 NAME

mysq_luptime - Plugin to monitor mysql\'s uptime.

=head1 CONFIGURATION

The following environment variables are used:

 mysqlopts - Options to pass to mysql
 mysqladmin - Path to mysqladmin (default: "mysqladmin")

If mysqladmin is not set, this plugin uses the system PATH to find
mysqladmin

=head1 AUTHOR

Lionel Félicité

=head1 LICENSE

MIT

=head1 MAGIC MARKERS

  #%# family=manual
  #%# capabilities=autoconf

=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

MYSQLOPTS="$mysqlopts";
MYSQLADMIN=${mysqladmin:-mysqladmin}

if [ "$1" = "autoconf" ]; then
        $MYSQLADMIN --version 2>/dev/null >/dev/null
        if [ $? -eq 0 ]
        then
                $MYSQLADMIN $MYSQLOPTS extended-status 2>/dev/null >/dev/null
                if [ $? -eq 0 ]
                then
                        echo yes
                        exit 0
                else
                        echo "no (could not connect to mysql)"
                fi
        else
                echo "no (mysqladmin not found)"
        fi
        exit 0
fi

if [ "$1" = "config" ]; then
        echo 'graph_title MySQL uptime'
        echo 'graph_category mysql'
        echo 'graph_title Uptime'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_scale no'
        echo 'graph_vlabel uptime in days'
        echo 'uptime.label uptime'
        echo 'uptime.draw AREA'
        print_warning uptime
        print_critical uptime
        exit 0
fi

($MYSQLADMIN $MYSQLOPTS extended-status 2>/dev/null || ( echo Mysql_uptime a a U)) | awk '/Uptime/ { printf "uptime.value %.2f\n",$4/86400}'
